# This Github workflow will check every hour for PRs with the lgtm label and will attempt to automatically merge them.
# If the hold label is present, it will block automatic merging.

name: "Prow merge on lgtm label"
on:
#  schedule:
#  - cron: "0 * * * *" # every hour
  pull_request:
    types:
      - labeled

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'lgtm')
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: 'squash'
